<?php return array(
    'root' => array(
        'name' => '__root__',
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'reference' => NULL,
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'reference' => NULL,
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v5.2.28',
            'version' => '5.2.28.0',
            'reference' => 'acba50393dd03da69a50226c139722af8b153b11',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'smarty/smarty-lexer' => array(
            'pretty_version' => 'v3.1.33',
            'version' => '3.1.33.0',
            'reference' => 'e0ee2739c93c717b18ed703a54073a8f55e9f646',
            'type' => 'library',
            'install_path' => __DIR__ . '/../smarty/smarty-lexer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
